### ISSUE TITLE
tacoRepo.findAll(PageRequest page).getContent() in the book

### ISSUE THREAD

**Issue by ghost** [allenlee820202/Spring-in-Action-5-Practice#1]
Hello, 
I'm not sure if you are a reader of this book or a proof-reader for Manning.
In the book, the author gives a really brief "/recent". The findAll(PageRequest page) method on the TacoRepository is the key. 
It looks like you imported PageRequest but didn't actually use it?
Thanks for explaining.

**Comment by bifork** [comment]
Adding `Page<Taco> findAll(Pageable page);` to TacoRepository would do. Thus the author's code is more concise. Closing this issue.

**Comment by allenlee820202** [comment]
Sorry for the code which leads to misunderstanding. The ```PageRequest``` actually did nothing in the Chapter 6 code. Code in Chapter 7 fixed this problem just as you mentioned.
